---
language: ruby

sudo: false

script: 'SPEC_OPTS="--format documentation" bundle exec rake validate lint spec'

matrix:
  fast_finish: true
  include:
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.7.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.8.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.9.0"
    - rvm: 2.4.0
      env: PUPPET_GEM_VERSION="~> 5.0"

notifications:
  email: false
