name    'ericsson-motd'
version '0.0.1'
source 'git@github.com:ericsson/puppet-module-motd.git'
author 'ericsson'
license 'Apache License, Version 2.0'
summary 'Manage MOTD'
description 'Manage /etc/motd, /etc/issue, and /etc/issue.net files'
project_page 'https://github.com/ericsson/puppet-module-motd/'

dependency 'puppetlabs/stdlib'
